/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a chat completion request
         * @description Non-streaming by default. Set `stream: true` to receive SSE events
         *     (same format as POST /v1/chat/stream).
         */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a streaming chat completion request
         * @description Always returns SSE events. Each event has a typed `event:` field
         *     (content, reasoning, tool_call, usage, done, error).
         */
        post: operations["chatStream"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available models
         * @description Returns models filtered to providers with configured API keys.
         */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatRequest: {
            /**
             * @description Model identifier. Use "provider/model" format (e.g., "anthropic/claude-sonnet-4-6")
             *     or just the model name for auto-detection (e.g., "claude-sonnet-4-6").
             * @example anthropic/claude-sonnet-4-6
             * @example gpt-5.4
             * @example gemini-3-flash-preview
             */
            model: string;
            /** @description Conversation messages */
            messages: components["schemas"]["Message"][];
            /**
             * @description If true on /v1/chat, returns SSE stream instead of JSON.
             * @default false
             */
            stream: boolean;
            config?: components["schemas"]["Config"];
            /**
             * @description Raw provider-specific JSON merged into the underlying request.
             *     Use this for features like Anthropic thinking, Gemini safety settings, etc.
             * @example {
             *       "thinking": {
             *         "type": "adaptive"
             *       },
             *       "output_config": {
             *         "effort": "high"
             *       }
             *     }
             */
            provider_config?: {
                [key: string]: unknown;
            };
        };
        Message: {
            /** @enum {string} */
            role: "system" | "user" | "assistant" | "tool" | "developer";
            /** @description Text content or array of content blocks */
            content?: string | Record<string, never>[] | null;
            /** @description For tool role messages, the ID of the tool call being responded to */
            tool_call_id?: string;
            /** @description Tool calls made by the assistant */
            tool_calls?: components["schemas"]["ToolCall"][];
        };
        /** @description Provider-agnostic configuration */
        Config: {
            /** @description Maximum output tokens */
            max_tokens?: number;
            /** Format: double */
            temperature?: number;
            /** Format: double */
            top_p?: number;
            top_k?: number;
            stop?: string[];
            /**
             * @description Controls reasoning/thinking depth across all providers
             * @enum {string}
             */
            reasoning_effort?: "low" | "medium" | "high";
        };
        ChatResponse: {
            /** @description Response ID from the provider */
            id: string;
            model: string;
            /** @description Which provider handled the request */
            provider: string;
            message: components["schemas"]["ResponseMessage"];
            /** @description Reasoning/thinking content if the model produced it */
            reasoning?: string | null;
            usage: components["schemas"]["Usage"];
            /** @description End-to-end latency in milliseconds */
            latency_ms: number;
        };
        ResponseMessage: {
            role: string;
            /** @description Text content or null */
            content: string | null;
            tool_calls?: components["schemas"]["ToolCall"][];
        };
        ToolCall: {
            id?: string;
            /** @enum {string} */
            type?: "function";
            function?: {
                name?: string;
                /** @description JSON-encoded arguments */
                arguments?: string;
            };
        };
        Usage: {
            input_tokens?: number;
            output_tokens?: number;
            /** @description Reasoning/thinking tokens used (if applicable) */
            reasoning_tokens?: number;
            total_tokens?: number;
        };
        /** @description SSE events emitted during streaming. Each event has a typed `event:` field. */
        StreamEvent: {
            /** @constant */
            type?: "content";
            text?: string;
        } | {
            /** @constant */
            type?: "reasoning";
            text?: string;
        } | {
            /** @constant */
            type?: "tool_call";
            id?: string;
            name?: string;
            arguments?: string;
        } | {
            /** @constant */
            type?: "usage";
            input_tokens?: number;
            output_tokens?: number;
            reasoning_tokens?: number;
            total_tokens?: number;
        } | {
            /** @constant */
            type?: "done";
        } | {
            /** @constant */
            type?: "error";
            message?: string;
        };
        ModelsResponse: {
            models: {
                /** @description Full model identifier (provider/name) */
                id: string;
                provider: string;
                /** @description Model name without provider prefix */
                name: string;
            }[];
        };
        HealthResponse: {
            status: string;
            /** @description List of configured providers */
            providers: string[];
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Chat completion response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Bad request (missing model, unknown provider) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Provider error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    chatStream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description SSE event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available models */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
